### ISSUE TITLE
When you provide a large value to client.write, it is received as an array.

### ISSUE THREAD

**Issue by anuraagvaidya** [kalm/kalm.js#11]
Sometimes,

```JS
client.write('test.data',{result:{type:'string', value:'<some large base64 string>'}});
```
Doing the above results in the loss of hierarchy of the object, and instead, the data is received as an array of bytes.

Sometimes the received object would is:
```JS
{result:{type:'string', value:'<some large base64 string>'}}
```

and sometimes it is:
```JS
[12,16,114,<numbers like that >]
```
What must be wrong? Is it returning a buffer-like object when the response is too long?

**Comment by fed135** [comment]
Can you show me the full code? 

It seems like the data is not being deserialized. (data is passed as UInt8Array)

**Comment by fed135** [comment]
Could not repro.
