### ISSUE TITLE
IPC Example?

### ISSUE THREAD

**Issue by electic** [kalm/kalm.js#32]
Is there an example of using IPC? Also, does it work across platforms like windows?

**Comment by fed135** [comment]
@electic Using one transport or another should have no impact on the overall syntax, you just need to follow the instructions in https://github.com/kalm/kalm.js/tree/master/packages/ipc

So your client/ server setup would be like this:

```
 
const kalm = require('kalm');
const ipc = require('@kalm/ipc');

const Client = kalm.connect({
  host: '0.0.0.0',
  port: 8800,
  transport: ipc({
    path: '/tmp/app.socket'
  }),
  routine: kalm.routines.realtime(),
});
```

This will bind the file descriptor handle to the file `/tmp/app.socket:8800`

Windows is supported, tho you'll have to specify a pathname that is in DOS format
